services:
  - type: web
    name: funland-bot
    runtime: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app -b 0.0.0.0:$PORT"
    envVars:
      - key: YANDEX_API_KEY
        value: AQVN1yUDXvnO8SFPcpT5yD4oWrQAol4Gx5GtQqYW
      - key: YANDEX_FOLDER_ID
        value: b1gl7ugev7botoao0fa6
      - key: FLASK_SECRET_KEY
        generateValue: true